defmodule When.Lexer do
  @moduledoc """
  Uses lexer generated by 'leex' erlang tool based on specification defined in
  "src/when_lexer.xrl" to break given string expression into a list of tokens
  suitable for further syntax analysis by Parser module.
  """

  def tokenize(string_expression) do
    string_expression
    |> to_charlist()
    |> :when_lexer.string()
    |> case  do
        {:ok, tokens, _} -> {:ok, tokens}

        error -> error
      end
  end
end
