defmodule When.Parser do
  @moduledoc """
  Uses parser generated by 'yecc' erlang tool based on specification defined in
  "src/when_parser.yrl" to performe syntax analysis on given tokens list and
  form abstract syntax tree which is later used by interpreter to evaluate expression.
  """

  def parse(tokens) do
    case :when_parser.parse(tokens) do
      {:ok, ast} -> {:ok, ast}
      error -> error
    end
  end
end
